[workspace]
members = [
    "indexer-lib",
    "protocol",
]
resolver = "3"


[workspace.dependencies]
anyhow = "1.0.98"
faster-hex = "0.10.0"
flume = "0.11.1"
futures-util = "0.3.31"
itertools = "0.14.0"
kaspa-core = "1.*"
kaspa-rpc-core = "1.*"
kaspa-wrpc-client = "1.*"
ringmap = "0.1.4"
rolling-file = "0.2.0"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
workflow-core = "0.18.0"

[patch.crates-io]
kaspa-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
kaspa-rpc-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
kaspa-wrpc-client = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
