[workspace]
members = ["indexer-lib"]
resolver = "3"


[workspace.dependencies]
kaspa-core = "1.*"
kaspa-rpc-core = "1.*"
kaspa-wrpc-client = "1.*"

anyhow = "1.0.98"
flume = "0.11.1"
indexmap = "2.10.0"
itertools = "0.14.0"
rolling-file = "0.2.0"
tokio = "1.45.1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[patch.crates-io]
kaspa-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
kaspa-rpc-core = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
kaspa-wrpc-client = { git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0" }
