[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
fjall = { workspace = true }
flume = { workspace = true }
kaspa-wrpc-client = { workspace = true }
parking_lot = { workspace = true }
tokio = { workspace = true, features = ["signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
workflow-core = { workspace = true }
rolling-file = { workspace = true }

indexer-lib = { path = "../indexer-lib" }