name: Manual Trigger Docker Build & Push
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker tag"
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # :{tag}, :{sha1}, :latest (if on main branch)
          tags: ${{ vars.DOCKER_REPO }}:${{ github.event.inputs.tag }},${{ vars.DOCKER_REPO }}:${{ github.sha }} ${{ github.ref != 'refs/heads/main' && '${{ vars.DOCKER_REPO }}:latest' || '' }}
